"""
ClassEval reward computation utilities.

Implements a subprocess-based unittest runner that returns detailed per-test outcomes,
and a helper to run tests on combined code (skeleton merged with completions).

Scoring (redesigned):
- Let V be the total number of methods in the class.
- lv1 (coverage): let x be the size of the union of all agents' selected method sets; score = 2 * (x / V).
  Special case: if (x / V) < 1/2, total reward = 0 for this sample.
- lv2 (total-picks control): let S = Σ_i |A_i| be the total number of functions generated by all agents.
  For 0 <= S <= 2V, define a concave-down quadratic with peak 2 at S=V and -2 at S=0 and S=2V:
    lv2(S) = 2 - 4 * ((S - V)^2) / V^2  (assuming V>0)
  If S > 2V: terminate this sample with reward = -INF immediately.
- lv3 (balance via variance): let N be the number of agents, and s_i the number of methods chosen by agent i.
  Target t = V/N, MSD = (1/N) * Σ (s_i - t)^2, MSD_max = (1/N) * V^2 * (1 - 1/N).
  Score R_bal = max(0, 1 - MSD / (MSD_max + eps)).
Total reward = lv1 + lv2 + lv3.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import textwrap
from typing import Any, Dict, List, Optional, Set, Tuple
import os
import math

def _combine_code(impl_code: str, test_code: str) -> str:
    return (impl_code or "").rstrip() + "\n\n" + (test_code or "").lstrip()


def run_unittests_with_details(impl_code: str, test_code: str, timeout: int = 40) -> Dict[str, Any]:
    """Run unittests with a custom TestResult that records per-test outcomes.

    Behavior:
    - First performs a syntax check on the merged code (implementation + tests).
    - If syntax fails, returns immediately without launching the subprocess test runner.
    - Otherwise, runs tests in an isolated temp directory and reports detailed outcomes.

    Returns a JSON-serializable dict including:
    - syntax_ok: bool
    - testsRun, passed, failures, errors, skipped
    - test_results: list of {id, outcome}
    - stdout, stderr, exit_code
    - timeout: bool
    """
    combined_code = _combine_code(impl_code, test_code)

    # Syntax check first (no formatting here; formatting is applied upstream after merge)
    try:
        compile(combined_code, "<combined>", "exec")
        syntax_ok = True
    except Exception as e:
        syntax_ok = False
        # Early return: do not run tests when syntax is invalid
        return {
            "syntax_ok": False,
            "timeout": False,
            "success": False,
            "testsRun": 0,
            "failures": 0,
            "errors": 1,
            "skipped": 0,
            "passed": 0,
            "stdout": "",
            "stderr": f"SyntaxError: {e}",
            "exit_code": None,
            "test_results": [],
        }

    runner_code = """
import json, sys, importlib.util, unittest, io, time, traceback, contextlib

class RecordingResult(unittest.TextTestResult):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.records = []
    def addSuccess(self, test):
        super().addSuccess(test)
        self.records.append({"id": str(test), "outcome": "passed"})
    def addFailure(self, test, err):
        super().addFailure(test, err)
        self.records.append({"id": str(test), "outcome": "failed"})
    def addError(self, test, err):
        super().addError(test, err)
        self.records.append({"id": str(test), "outcome": "error"})
    def addSkip(self, test, reason):
        super().addSkip(test, reason)
        self.records.append({"id": str(test), "outcome": "skipped"})

def main(py_file):
    import importlib.util
    spec = importlib.util.spec_from_file_location("task_module", py_file)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    suite = unittest.defaultTestLoader.loadTestsFromModule(mod)
    stream = io.StringIO()
    with contextlib.redirect_stdout(stream), contextlib.redirect_stderr(stream):
        runner = unittest.TextTestRunner(stream=stream, verbosity=2, resultclass=RecordingResult)
        res = runner.run(suite)
    out = stream.getvalue()
    result = dict(
        testsRun=res.testsRun,
        failures=len(res.failures),
        errors=len(res.errors),
        skipped=len(res.skipped),
        passed=res.testsRun - len(res.failures) - len(res.errors) - len(res.skipped),
        success=res.wasSuccessful(),
        test_results=getattr(res, "records", []),
        output=out,
    )
    print(json.dumps(result))

if __name__ == "__main__":
    try:
        main(sys.argv[1])
    except SystemExit as e:
        import traceback as _tb
        print(json.dumps({"exception": "SystemExit", "code": getattr(e, 'code', None), "traceback": _tb.format_exc()}))
        sys.exit(3)
    except Exception as e:
        import traceback as _tb
        print(json.dumps({"exception": str(e), "traceback": _tb.format_exc()}))
        sys.exit(2)
"""

    # Run tests in an isolated temporary working directory so that any
    # file system side effects from user code or tests do not pollute the repo root.
    # If a job id is available (e.g., SLURM_JOB_ID), group temp dirs under it to
    # avoid collisions across concurrent processes while keeping per-call isolation.
    base_tmp = os.environ.get("CLASSEVAL_TMP_BASE", tempfile.gettempdir())
    job_id = os.environ.get("SLURM_JOB_ID") or os.environ.get("JOB_ID")
    # Support placeholder in base path: ".../[jobid]/tmp"
    if isinstance(base_tmp, str) and job_id and "[jobid]" in base_tmp:
        try:
            base_tmp = base_tmp.replace("[jobid]", str(job_id))
        except Exception:
            pass
    tmp_parent = base_tmp
    try:
        tmp_parent = os.path.abspath(tmp_parent)
    except Exception:
        pass
    try:
        os.makedirs(tmp_parent, exist_ok=True)
    except Exception:
        pass

    with tempfile.TemporaryDirectory(dir=tmp_parent) as tmpdir:
        # Normalize tmpdir and pass relative payload to runner
        try:
            tmpdir_abs = os.path.abspath(tmpdir)
        except Exception:
            tmpdir_abs = tmpdir
        payload_name = "task_module_payload.py"
        py_path = os.path.join(tmpdir_abs, payload_name)
        with open(py_path, "w", encoding="utf-8") as fh:
            fh.write(combined_code)
        try:
            proc = subprocess.run(
                [sys.executable, "-c", runner_code, payload_name],
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
                cwd=tmpdir_abs,
            )
        except subprocess.TimeoutExpired:
            return {
                "syntax_ok": syntax_ok,
                "timeout": True,
                "success": False,
                "testsRun": 0,
                "failures": 0,
                "errors": 1,
                "skipped": 0,
                "passed": 0,
                "stdout": "",
                "stderr": "TimeoutExpired",
                "exit_code": None,
                "test_results": [],
            }

    stdout = (proc.stdout or "").strip()
    stderr = (proc.stderr or "").strip()

    try:
        res = json.loads(stdout) if stdout else {}
    except json.JSONDecodeError:
        res = {
            "success": False,
            "testsRun": 0,
            "failures": 0,
            "errors": 1,
            "skipped": 0,
            "passed": 0,
            "parse_error": True,
            "output": stdout,
        }

    res.update(
        {
            "syntax_ok": syntax_ok,
            "timeout": False,
            "stdout": stdout,
            "stderr": stderr,
            "exit_code": proc.returncode,
        }
    )
    return res


# ---------- Reward Factory (multi-agent merge + scoring) ----------
from typing import Callable  # re-export type for signatures
from LLM_Collab_Module_Completion.utils.data import (
    extract_class_name,
    extract_incomplete_methods,
)
from LLM_Collab_Module_Completion.utils.parse_completion import extract_method_snippets
from LLM_Collab_Module_Completion.loggers.reward_logger import RewardLogger


def _compute_call_graph_components(source_code: str, class_name: str, methods: Set[str]) -> List[Set[str]]:
    """Build undirected connected components of method-call graph within the class.

    Edges between methods u-v if method u contains a call to v (e.g., self.v(...)).
    Only consider methods within the provided `methods` set.
    Returns a list of components (each as a set of method names).
    """
    comps: List[Set[str]] = []
    if not source_code or not class_name or not methods:
        return comps
    try:
        import ast
    except Exception:
        return comps
    try:
        tree = ast.parse(source_code)
    except Exception:
        return comps

    # Locate class
    target = None
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            target = node
            break
    if target is None:
        return comps

    # Build adjacency
    adj: Dict[str, Set[str]] = {m: set() for m in methods}

    def collect_calls(fn: "ast.FunctionDef") -> Set[str]:
        called: Set[str] = set()
        for ch in ast.walk(fn):
            if isinstance(ch, ast.Call):
                f = ch.func
                # self.method(...) or obj.method(...)
                if isinstance(f, ast.Attribute):
                    name = f.attr
                    if name in methods:
                        called.add(name)
                # direct function call (unlikely in class method context)
        return called

    for item in target.body:
        if isinstance(item, (ast.FunctionDef,)):
            src = item.name
            if src not in methods:
                continue
            outs = collect_calls(item)
            for dst in outs:
                if dst in methods and dst != src:
                    adj[src].add(dst)
                    adj[dst].add(src)

    # Connected components on adjacency
    seen: Set[str] = set()
    for m in methods:
        if m in seen:
            continue
        stack = [m]
        comp: Set[str] = set()
        while stack:
            u = stack.pop()
            if u in seen:
                continue
            seen.add(u)
            comp.add(u)
            for v in adj.get(u, set()):
                if v not in seen:
                    stack.append(v)
        if comp:
            comps.append(comp)
    return comps

# count rate of passing lv1 + lv2
_count_total, _count_pass_lv1_2, _count_pass_lv0 = 0, 0, 0

def get_reward_function(strategy, num_agents: int) -> Callable[..., List[float]]:
    """Return a reward function implementing the redesigned lv1+lv2+lv3 scoring.

    - V = total number of class methods requiring implementation
    - lv1 = 2 * (|union of chosen methods across agents| / V)
      Special case: if coverage < 1/2 then reward = 0 for this sample
    - lv2 = total-picks control:
      Let S = Σ_i |A_i| be the total number of functions generated by all agents.
        * If S > 2V: terminate this sample early with total reward = -INF (=-1)
        * If 0 <= S <= 2V: lv2(S) = 2 - 4 * ((S - V)^2) / V^2 (assuming V>0)
    - lv3 = balance based on variance of |A_i| around t = V/N, with
      MSD = (1/N) * Σ (s_i - t)^2 and MSD_max = (1/N) * V^2 * (1 - 1/N),
      R_bal = max(0, 1 - MSD/(MSD_max + eps))
    Total reward = lv1 + lv2 + lv3
    """

    def reward_wrapper(*agent_completions, batch_items=None, prompts=None):
        # Use module-level counters for pass rate tracking
        global _count_total, _count_pass_lv1_2, _count_pass_lv0
        if not agent_completions:
            return []
        batch_size = len(agent_completions[0])
        rewards: List[float] = []

        for i in range(batch_size):
            example = {}
            try:
                example = batch_items[i] if batch_items is not None else {}
            except Exception:
                pass

            skeleton: str = example.get("skeleton", "")
            test_code: str = example.get("test", "")
            class_name = extract_class_name(skeleton) or ""
            method_names = extract_incomplete_methods(skeleton)

            partition = strategy.partition(example)

            agent_texts: List[str] = []
            A_sets: List[Set[str]] = []
            for agent_idx in range(num_agents):
                comp_text = ""
                try:
                    comp_text = agent_completions[agent_idx][i]
                except Exception:
                    comp_text = ""
                agent_texts.append(comp_text)
                parsed_all = extract_method_snippets(comp_text or "", allowed_methods=set(method_names))
                A_sets.append(set(parsed_all.keys()))

            INF = 1
            _count_total += 1

            # Early penalty: if any agent generated zero functions, assign -2 and skip
            try:
                if any((len(s) if s is not None else 0) == 0 for s in A_sets):
                    rewards.append(-INF * 2)
                    continue
            except Exception:
                # fall back to normal flow on unexpected structure
                pass
            
            _count_pass_lv0 += 1

            # New reward rules (lv1 + lv2)
            V_set: Set[str] = set(method_names)
            V = len(V_set)
            if V <= 0:
                rewards.append(-INF)
                continue

            # lv1: 2 * (|union| / V); if coverage < 1/2 => reward 0
            union_size = len(set().union(*A_sets)) if A_sets else 0
            coverage_ratio = union_size / V
            if coverage_ratio < 0.35:
                rewards.append(-INF)
                continue
            
            lv1 = 2.0 * coverage_ratio
            if coverage_ratio < 0.5:
                lv1 = 0

            # lv2: constrain total picks S = sum_i |A_i|
            S_total = sum(len(s) for s in A_sets)
            # Early termination if total picks exceed 2V
            if S_total > 2 * V:
                rewards.append(-INF)
                continue
            # Quadratic, concave-down, passing (0,-2), (V,2), (2V,-2)
            # lv2(S) = 2 - 4 * ((S - V)^2) / V^2
            if V > 0:
                dv = float(S_total) - float(V)
                lv2 = 2.0 - 4.0 * (dv * dv) / (float(V) * float(V))
            else:
                lv2 = -2.0 * INF
            # numerical guard
            if lv2 > 2.0:
                lv2 = 2.0
            if lv2 < -2.0 * INF:
                lv2 = -2.0 * INF

            # get bonus after passing lv1, lv2
            # lv_bonus = 0.2

            # lv3: balance via entropy of chosen set sizes
            s_list = [float(int(x)) for x in counts]
            N = int(num_agents) if num_agents > 0 else 1
            t = float(V) / float(N)
            msd = (sum((si - t) ** 2 for si in s_list) / float(N)) if N > 0 else 0.0
            msd_max = (1.0 / float(N)) * (float(V) ** 2) * (1.0 - 1.0 / float(N)) if N > 0 else 0.0
            eps = 1e-8
            ratio = 0.0 if msd_max <= 0 else (msd / (msd_max + eps))
            lv3 = 3.5 * max(0.0, 1.0 - ratio) - 0.5

            _count_pass_lv1_2 += 1
            total = float(lv1 + lv2 + lv3)

            print('=' * 50)
            print(lv1, lv2, lv3)
            print(_count_pass_lv0 / _count_total)
            print(_count_pass_lv1_2 / _count_total)
            print('=' * 50)

            # Optional eval logging (reuse field names for compatibility)
            try:
                phase = str(example.get("phase", "")).lower() if isinstance(example, dict) else ""
            except Exception:
                phase = ""
            if phase == "eval":
                try:
                    RewardLogger.log_ce_levels(
                        cover=lv1,
                        overlap=lv2,
                        balance=lv3,
                        components=0.0,
                        total=total,
                        step=None,
                        commit=False,
                        prefix="eval/ce_reward",
                    )
                except Exception:
                    pass

            # Preview generations: print each agent's code and number of functions parsed
            try:
                preview_limit = 40000
                task_id = example.get("task_id")
                header = f"[gen] class={class_name or 'unknown'} task_id={str(task_id) if task_id is not None else 'N/A'}"
                print(header, flush=True)
                print(f"total funcs: {V}")
                for aidx, text in enumerate(agent_texts):
                    funcs_cnt = len(A_sets[aidx]) if aidx < len(A_sets) else 0
                    snippet = (text or "")[:preview_limit]
                    if text and len(text) > preview_limit:
                        snippet += "..."
                    print(f"[agent_{aidx}] funcs={funcs_cnt}", flush=True)
                    # print(f"[agent_{aidx}] code:\n{snippet}", flush=True)
            except Exception:
                pass

            rewards.append(total)

        return rewards

    return reward_wrapper
